### ISSUE TITLE
Need to exclude library folders from github

### ISSUE THREAD

**Issue by bunjii** [bunjii/PTKTest#14]
urgent.

**Comment by AndersRod** [comment]
Make sure to remove the historic data of the lib as well ref: https://help.github.com/articles/removing-files-from-a-repository-s-history/ 
Also, this would be a good chance to dig into .gitignore

**Comment by bunjii** [comment]
@johnhaddalmork @marcinluczkowski 

I changed the "Library" folder's location 2 directories up, and excluded from the github. Please relocate the Library folder accordingly in your local and pull the latest 'TYOWS'. 

I'll tackle on historic data as Anders suggested above.

**Comment by bunjii** [comment]
I deleted library info from the history. I'll close this post soon.
