### ISSUE TITLE
Priority List

### ISSUE THREAD

**Issue by bunjii** [bunjii/PTKTest#37]
I think we need to be more clear about priority list of member. Current "materializer" has an input for list of integer but I can't imagine a way it works. Hence, the followings:  

Priority list will be introduced in order to determine which member(s) will be cut against others at each node. We have decided at Ver. 0.5 we will focus on this way only, at Ver. 1.0 we will start think about the opposite way (= priority will be determined according to the result of structural analysis.)  

Suppose we have a simple truss structure, and we have a priority list shown at the right side of the page 1 (below).  We can expect the result cut shown at the bottom of the page 1.  

![0001](https://user-images.githubusercontent.com/16072693/37636900-1aeb6f4a-2c48-11e8-9433-65972a1e1b9a.jpg)  

In order to achieve this, there are two options occurred to me.  One is to define this at "materializer" component, and the other at "Assemble Model" component. For the former way, the materializer will have an input (type: item, integer) and for the latter, we don't need priority list in the materilizer but instead we will need a text item input in the "assemble model" component.  

![0002](https://user-images.githubusercontent.com/16072693/37636902-1c7e474c-2c48-11e8-8166-a5ae3d8278f4.jpg)

I don't really have preference for this, but I would like to fix it. Let me know your opinion, so we can go on.

**Comment by AndersRod** [comment]
I was mentioning this earlier, but I was wondering if there is any benefit in organizing the priority / relationship between each member in a way so it can be visualized as a graph.
Here is the reference, I was talking about: https://vimeo.com/166203087 Skip forward to 17:15

**Comment by bunjii** [comment]
Thanks Anders, I think this is highly relevant to what we are going to develop. I understood as it is to analyse / visualize the dependency structure among members. I'll put this in the wishlist for Ver. 1.0., for not immediately imitating it, but to discuss what can be the benefit for visualizing this obscured structure in a project using PTK.

**Comment by bunjii** [comment]
Why don't we proceed with the 2nd option, i.e. to input the list in the "Assemble", for Ver. 0.5. in case none of us have preference? I think that's simpler to implement. 

To do: 
- remove the input for the priority list on Materializer
- to prepare input for the list on Assemble as an item
- to store the priority list data somewhere. presumably by making a field to store it in the Element class by interpreting the list and apply some integer value for each element...

**Comment by bunjii** [comment]
I reopened this to keep track on the implementation of this function.

**Comment by bunjii** [comment]
![capture](https://user-images.githubusercontent.com/16072693/39853390-f78cc19c-545c-11e8-8da9-e1f1e5cd4c30.PNG)

this has been implemented. 
sample truss file attached below.
[ptk_test_truss_10May.zip](https://github.com/bunjii/PTK/files/1990452/ptk_test_truss_10May.zip)
